# 1. Introduction to NumPy

## What is NumPy?

NumPy stands for **Numerical Python**. It is a powerful Python library used to perform fast and efficient numerical computations. NumPy provides support for arrays, matrices, and a wide range of mathematical operations.

NumPy is widely used in **Artificial Intelligence, Machine Learning, and Data Science** because most models work with numerical data, and NumPy makes handling such data easier and faster.

👉 **Python lists become slow when working with large amounts of data**, whereas **NumPy arrays are much faster** and perform close to the speed of the C programming language.

---

# 2. Understanding the `ndarray` Object

## What is an ndarray?

`ndarray` stands for **N-dimensional array**.  
This means we can create arrays with one dimension (1D), two dimensions (2D), three dimensions (3D), or even higher dimensions.

The `ndarray` is the core data structure of NumPy and is designed to store large datasets efficiently while allowing fast mathematical operations.


In [ ]:
import numpy as np 
arr = np.array([1,3,4])
print(arr)

[1 3 4]


## Why do we use `ndarray`?

The `ndarray` is used because it allows **very fast calculations** compared to traditional Python data structures.

It **uses less memory** while storing large numerical datasets, which makes programs more e


## Data Types in NumPy

NumPy stores **all elements of an array using the same data type**, which helps improve performance and memory efficiency.

Because of this uniform data type system, NumPy can perform mathematical operations much faster than regular Python lists.

### Common NumPy Data Types

- **int32, int64** → Used for integer values  
- **float32, float64** → Used for decimal (floating-point) numbers  
- **bool** → Used for True or False values  
- **str** → Used for string values  


In [196]:
arr = np.array([1,2,3,4] , dtype="float")
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float64


### Array Attributes

In [ ]:
arr = np.array([1,3,4])
arr.ndim    # dimensions batata hai output = 1
arr.shape   # rows aur columns batata hai output = (3,)
arr.size    # total elements output = 3
arr.dtype   # data type output = dtype('int64')

dtype('int32')

### Array Creation Techniques

(a) Array from List

In [201]:
np.array([1, 2, 3])

array([1, 2, 3])

(b) Zero Array

In [202]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

(c) Ones Array

In [203]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

(d) Range Based Arrays

In [204]:
np.arange(0, 10, 2)  # start, stop, step

array([0, 2, 4, 6, 8])

(e) Linespace

In [205]:
np.linspace(0, 1, 5)  # start, stop, number of elements

array([0.  , 0.25, 0.5 , 0.75, 1.  ])