# 1. Introduction to NumPy

## What is NumPy?

NumPy stands for **Numerical Python**. It is a powerful Python library used to perform fast and efficient numerical computations. NumPy provides support for arrays, matrices, and a wide range of mathematical operations.

NumPy is widely used in **Artificial Intelligence, Machine Learning, and Data Science** because most models work with numerical data, and NumPy makes handling such data easier and faster.

👉 **Python lists become slow when working with large amounts of data**, whereas **NumPy arrays are much faster** and perform close to the speed of the C programming language.

---

# 2. Understanding the `ndarray` Object

## What is an ndarray?

`ndarray` stands for **N-dimensional array**.  
This means we can create arrays with one dimension (1D), two dimensions (2D), three dimensions (3D), or even higher dimensions.

The `ndarray` is the core data structure of NumPy and is designed to store large datasets efficiently while allowing fast mathematical operations.


In [208]:
#!pip install numpy
import numpy as np 
arr = np.array([1,3,4])
print(arr)

[1 3 4]


## Why do we use `ndarray`?

The `ndarray` is used because it allows **very fast calculations** compared to traditional Python data structures.

It **uses less memory** while storing large numerical datasets, which makes programs more e


## Data Types in NumPy

NumPy stores **all elements of an array using the same data type**, which helps improve performance and memory efficiency.

Because of this uniform data type system, NumPy can perform mathematical operations much faster than regular Python lists.

### Common NumPy Data Types

- **int32, int64** → Used for integer values  
- **float32, float64** → Used for decimal (floating-point) numbers  
- **bool** → Used for True or False values  
- **str** → Used for string values  


In [209]:
arr = np.array([1,2,3,4] , dtype="float")
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float64


### Array Attributes

In [210]:
arr = np.array([1,3,4])
arr.ndim    # dimensions batata hai output = 1
arr.shape   # rows aur columns batata hai output = (3,)
arr.size    # total elements output = 3
arr.dtype   # data type output = dtype('int64')

dtype('int32')

### Array Creation Techniques

(a) Array from List

In [211]:
np.array([1, 2, 3])

array([1, 2, 3])

(b) Zero Array

In [212]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

(c) Ones Array

In [213]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

(d) Range Based Arrays

In [214]:
np.arange(0, 10, 2)  # start, stop, step

array([0, 2, 4, 6, 8])

(e) Linespace

In [215]:
np.linspace(0, 1, 5)  # start, stop, number of elements

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**2D arrays and 3D arrays**

In [217]:
# 2D array
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [218]:
# 3D array 
arr_3d = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(arr_3d)
print(arr_3d.ndim)  # dimensions

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


### Indexing and Slicing 

1D Array

In [222]:
arr = np.array([1,2,3,4])
# slicing single value
print(arr[0])   # first element
#slicing multiple values 
print(arr[0:3])

1
[1 2 3]


2D Array

In [231]:
arr2d = np.array([[1,2],
                  [3,4],
                  [5,6],
                  [7,8],
                  [9,10]])
print(arr2d[0,1])   # first row, second column
print("-"*20)
print(arr2d[1:3, 0:2])  # slicing rows and columns
print("-"*20)
print(arr2d[3:5,0:2])
print("-"*20)


2
--------------------
[[3 4]
 [5 6]]
--------------------
[[ 7  8]
 [ 9 10]]
--------------------


### Broadcasting 
Operations perform between different shapes of arrays without using loop.

In [232]:
arr2d = np.array([[1,2],
                  [3,4],
                  [5,6],
                  [7,8],
                  [9,10]])

print(arr2d + 1) # add 1 to each element

[[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


### Iterating over Arrays


In [235]:
for row in arr2d: # iterate through rows
    for value in row: # iterate through each value in row
        print(value)

1
2
3
4
5
6
7
8
9
10


### Array Manipulation 
1. Reshape : It is used to change the shape of array.

In [238]:
arr = np.array([1,2,3,4])
new_arr = arr.reshape(2,2)
print(new_arr)  # reshape(rows , columns )

[[1 2]
 [3 4]]


2. Flatten :  Multidimensional array convert into 1 Dimensional array.

In [239]:
pre_arr = new_arr.flatten()
print(pre_arr)

[1 2 3 4]


### Arithmetic and Mathematical Operations 

In [243]:
a = np.array([9, 36, 81])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(np.sqrt(a))
print(np.mean(a))


[13 41 87]
[ 36 180 486]
[3. 6. 9.]
42.0


### Statistical Functions 

In [254]:
arr = np.array([4, 5, 6])
print("Mean of arr is -----> " ,np.mean(arr)) # mean of array
print("Median of arr is ---> ", np.median(arr)) # median of array
print("Standard Deviation of arr -->", np.std(arr)) # standard Deviation
print("Sum of elements in array is -->", np.sum(arr)) # calculate sum of elements

Mean of arr is ----->  5.0
Median of arr is --->  5.0
Standard Deviation of arr --> 0.816496580927726
Sum of elements in array is --> 15


### Sorting , Searching and Counting 

In [259]:
arr = np.array([6,2,6,4,7,2,0,2,4]) 
print(np.sort(arr)) # output : [0 2 2 2 4 4 6 6 7]
print(np.argmax(arr))
print(np.argmin(arr))
print(np.unique(arr))


[0 2 2 2 4 4 6 6 7]
4
6
[0 2 4 6 7]


### Logical Function

In [260]:
arr > 2

array([ True, False,  True,  True,  True, False, False, False,  True])

In [264]:
np.any(arr>7)

False

In [262]:
np.all(arr>5)

False

### Binary and String Functions 
Low-level operations aur text preprocessing ke liye use hoti hain.

In [266]:
np.binary_repr(10)

'1010'

In [268]:
print(np.char.upper(["ai","city"]))

['AI' 'CITY']


### Matrix Operations 
Dot product 

In [274]:
a = np.array([[1,2],
             [3,4]])
b = np.array([[4, 5],
             [6,7]])
#1st method
c = a@b
print(c)
print("-"*40)
#2nd method 
print(np.dot(a,b))


[[16 19]
 [36 43]]
----------------------------------------
[[16 19]
 [36 43]]


### Copy and view

In [285]:
arrr = np.array([1,2,3])
d = np.array([2,3,4])
#view original data ko change krta ha 
d = arrr.view()
print(d)
print(arrr)


[1 2 3]
[1 2 3]


In [286]:
arrrr = np.array([1,2,3])
e = np.array([2,3,4])
#copy :Copy independent hoti hai, original safe rehta hai.
e = arrrr.copy()
print(arrrr)
print(e)

[1 2 3]
[1 2 3]


### Linear Algebra in Numpy

In [288]:
# Creating 2x3 matrix
matrix = np.array([[0,1,2],[3,4,5]])
print("Matrix\n",matrix)

Matrix
 [[0 1 2]
 [3 4 5]]


**Transpose**
Convert rows into columns and columns into rows

In [290]:
matrix = np.array([[0,1,2],[3,4,5]])
print("Matrix\n",matrix)
print("*"*40)
#transposing the matrix
transpose_matrix = matrix.T
print(transpose_matrix)

Matrix
 [[0 1 2]
 [3 4 5]]
****************************************
[[0 3]
 [1 4]
 [2 5]]


**Determinant** of the matrix

In [295]:
matrix = np.array([[1,2],[3,4]])
print("Determinant of Matrix\n", np.linalg.det(matrix))

Determinant of Matrix
 -2.0000000000000004


**Inverse** of the matrix.

In [296]:
matrix = np.array([[1,2],[3,4]])
print("Inverse of Matrix\n", np.linalg.inv(matrix))

Inverse of Matrix
 [[-2.   1. ]
 [ 1.5 -0.5]]


**Eigenvalues and Eigenvectors Computing**

In [299]:
matrix = np.array([[1,2],[3,4]])
eigenvalues , eigenvectors = np.linalg.eig(matrix)
print("eigenvalues : ",eigenvalues)
print("eigenvectors  :\n ",eigenvectors)

eigenvalues :  [-0.37228132  5.37228132]
eigenvectors  :
  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Solving **Linear Systems** <br>
`Ax=b` , where , A represents matrix and b is a vector.

In [301]:
A = np.array([[3,1],[1,2]])
b = np.array([9,8])

#solving linear system Ax=b 

x = np.linalg.solve(A,b)
print("Solution of the linear system : ",x)

Solution of the linear system :  [2. 3.]


### Singular Value Decomposition (SVD)
SVD is a factorization of a matrix into three matrices:
- V  (the left singularvectors)
- S (the singular values) 
-  V (the right singular vectors). <BR>It is useful
in various applications, including signal processing and statistics

In [305]:
A = np.array([[3,1],[1,2]])
U,S,V = np.linalg.svd(A)
print("Sigma values  :" , S)
print("*"*40)
print("U matrix :" ,U)
print("*"*40)
print("V  matrix : ",V)

Sigma values  : [3.61803399 1.38196601]
****************************************
U matrix : [[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]
****************************************
V  matrix :  [[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]


**Computing Norms** <br>
Norms measurethe size or length of vectors and matrices, helping quantify their magnitude


In [308]:
A = np.array([[3,1],[1,2]]) 

#Frobenius norm
norm = np.linalg.norm(A,'fro')
print("Frobenius norm of A : ", norm)

# L2 norm (Euclidean norm)
b = np.array([9,8])
l2_norm = np.linalg.norm(b)
print("L2 norm of b :",l2_norm)

Frobenius norm of A :  3.872983346207417
L2 norm of b : 12.041594578792296


## Handle Missing Value

In [312]:
array = np.array([1,2,3,4,5,np.nan,6,7,3,np.nan])
# check missing value
is_nan = np.isnan(array)
print(array)
print(is_nan)

[ 1.  2.  3.  4.  5. nan  6.  7.  3. nan]
[False False False False False  True False False False  True]


 Replacing Missing data 

In [315]:
print(array)
filled_array = np.nan_to_num(array,nan=0)
print(filled_array)

[ 1.  2.  3.  4.  5. nan  6.  7.  3. nan]
[1. 2. 3. 4. 5. 0. 6. 7. 3. 0.]


Removing Missing values 

In [ ]:
print("original array is :",array)
#removing missing value
cleaned_array = array[~np.isnan(array)]
print("cleaned array is ",cleaned_array)

original array is : [ 1.  2.  3.  4.  5. nan  6.  7.  3. nan]
cleaned array is  [1. 2. 3. 4. 5. 6. 7. 3.]
