In [ ]:
#!pip install numpy

In [62]:
import numpy as np 

In [63]:
#1-Dimensional Array
a = np.array([1,2,3])
#2d array
b = np.array([[1,2],[3,4]])
#Specify Minimum Dimensions
c = np.array([1,2,3,4,5],ndmin=2)
#Specify Data Type 
d = np.array([1,2,3],dtype=complex)

Datatype of an Array 

In [64]:
print("Array: ",a)
# dtype is used to check dataype of array
print("Datatype of Array a is :", a.dtype)

Array:  [1 2 3]
Datatype of Array a is : int32


Convert Datatype of Numpy Arrays

In [65]:
print("Original Array of a : ",a.dtype)
#Converting To float
#change dataype of a 
a_float = a.astype(np.float32)
print("Converstion array of a :",a_float)
print("Data type of a_float = ",a_float.dtype)


Original Array of a :  int32
Converstion array of a : [1. 2. 3.]
Data type of a_float =  float32


Handling Conversion Error 

In [66]:
 
arr= np.array(['1','2','three','4','5','6'])
print("original arr:",arr)
print("original array dataype:",arr.dtype)
print("-"*67)
def safe_convert(arr,target_type):
    try:
        return arr.astype(target_type)

        pass
    except ValueError as e:
        print("Coversion error ", e)



#Attempting to convert to integar.
arr_int = safe_convert(arr,np.int32)
if arr_int is not None:
    print(arr_int)
    print(arr_int.dtype)
else:
    print("Conversion failed.")




original arr: ['1' '2' 'three' '4' '5' '6']
original array dataype: <U5
-------------------------------------------------------------------
Coversion error  invalid literal for int() with base 10: 'three'
Conversion failed.


Numpy Array Creation Routines

Using numpy.ones() Function
 Onthe other hand, the numpy.ones() function creates an array where all
elements are set to 1.
 Itaccepts three main parameters: shape, dtype, and order

In [67]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [68]:
print(np.ones((2,2)))

[[1. 1.]
 [1. 1.]]


Using numpy.arange() Function
 The numpy.arange() function creates an array by generating a sequence
of numbers based on specified start, stop, and step values.
 Itis similar to Python's built-in range() function..

In [69]:

print(np.arange(1,10,2))

[1 3 5 7 9]


Using numpy.linspace() Function
 We can even use the numpy.linspace() function to create an array by
specifying the start, stop, and the number of elements we want.
 Thearray created by 

In [70]:
print(np.linspace(1,11,5))

[ 1.   3.5  6.   8.5 11. ]


Using random.rand() Function
 Alternatively, we can use the numpy.random.rand() function for creating
an array by specifying the dimensions of the array as parameters.
 This function is used to create an array of specified shape filled with
random values sampled from a uniform distribution over [0, 1)

In [71]:
np.random.rand(3,2)

array([[0.25908999, 0.63642347],
       [0.04834561, 0.73950321],
       [0.94251878, 0.55250996]])

Using numpy.empty() Function
 We can create a NumPy array using the numpy.empty() function by
specifying the shape of the array as parameters.
 Unlike numpy.zeros() function and numpy.ones() function, which
initialize array elements to zero and one respectively, the numpy.empty()
function does not initialize the elements.
 Instead, it allocates the memory required for the array without setting any
values.

In [72]:
empty_array = np.empty((2,3))
print("Empty Array : \n",empty_array)

Empty Array : 
 [[0.25908999 0.63642347 0.04834561]
 [0.73950321 0.94251878 0.55250996]]


Using numpy.full() Function
 Using the numpy.full() function, we can create an array with a desired
shape and set all the elements in it to a specific value.

In [73]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

# Numpy - Array Manipulation 
- Changing Shape

In [74]:
arr_1 = np.array([1,2,3,4,5,6])

In [85]:
c_arr_1 = arr_1.reshape(2,3)
print(c_arr_1)

[[1 2 3]
 [4 5 6]]


Transpose

In [86]:
print(c_arr_1.T)

[[1 4]
 [2 5]
 [3 6]]


### joining Arrays


In [89]:
arr_2 = np.array([7,8,9])
arr_3 = np.array([1,2,3])


In [91]:
np.concatenate((arr_1,arr_2,arr_3))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3])